version: '3'
services:
  ######################################################################
  servicesdb:
    hostname: servicesdb
    image: mysql:latest
    container_name: servicesdb
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=taskdb
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - /database:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    ports:
      - "13306:3306"
    networks:
      - app-network
  ######################################################################
  taskservice1:
    hostname: taskservice1
    depends_on:
      - servicesdb
      - taskserver
    image: eliivanov66/taskservice:0.0.5
    container_name: taskservice1
    restart: unless-stopped
    ports:
      - "8191:8080"
    networks:
      - app-network
  ######################################################################
  taskservice2:
    hostname: taskservice2
    depends_on:
      - taskservice1
      - servicesdb
      - taskserver
    image: eliivanov66/taskservice:0.0.5
    container_name: taskservice2
    restart: unless-stopped
    ports:
      - "8192:8080"
    networks:
      - app-network
  ######################################################################
  taskservice3:
    hostname: taskservice3
    depends_on:
      - taskservice2
      - servicesdb
      - taskserver
    image: eliivanov66/taskservice:0.0.5
    container_name: taskservice3
    restart: unless-stopped
    ports:
      - "8193:8080"
    networks:
      - app-network
  ######################################################################
  taskserver:
    hostname: taskserver
    image: eliivanov66/taskserver:0.0.5
    container_name: taskserver
    restart: unless-stopped
    ports:
      - "8190:8761"
    networks:
      - app-network
  ######################################################################
  taskgateway:
    hostname: taskgateway
    depends_on:
      - taskserver
      - taskservice1
      - taskservice2
      - taskservice3
    image: eliivanov66/taskgateway:0.0.5
    container_name: taskgateway
    restart: unless-stopped
    ports:
      - "8180:8180"
    networks:
      - app-network
  ######################################################################
#  docker run -p 9090:9090 -v .\prometheus.yml:\etc\prometheus\prometheus.yml prom/prometheus
  prometheus:
    hostname: prometheus
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "8200:9090"
    networks:
      - app-network

  grafana:
    hostname: grafana
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "8201:3000"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge